<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>GunsawLevelEditorTools</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <GameDir Condition="'$(GameDir)' == ''">C:\Games\Gunsaw</GameDir>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all" />
    <Compile Include="..\GunsawImageCode\ArtCode.cs" Link="ArtCode.cs" />
    <Reference Include="BepInEx"><HintPath>$(GameDir)\BepInEx\core\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp" Publicize="true"><HintPath>$(GameDir)\Gunsaw_Data\Managed\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>$(GameDir)\Gunsaw_Data\Managed\Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(GameDir)\Gunsaw_Data\Managed\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameDir)\Gunsaw_Data\Managed\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(GameDir)\Gunsaw_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>$(GameDir)\Gunsaw_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.JSONSerializeModule"><HintPath>$(GameDir)\Gunsaw_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.Physics2DModule"><HintPath>$(GameDir)\Gunsaw_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.2D.SpriteShape.Runtime"><HintPath>$(GameDir)\Gunsaw_Data\Managed\Unity.2D.SpriteShape.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(GameDir)\Gunsaw_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>$(GameDir)\Gunsaw_Data\Managed\UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>$(GameDir)\Gunsaw_Data\Managed\UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
